version: "3.8"

services:
  db:
    container_name: db
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
volumes:
  mysql-data:


